export const ADD_CATEGORYNAME = "ADD_CATEGORYNAME";
export const REMOVE_CATEGORYNAME = "REMOVE_CATEGORYNAME";
export const EDIT_CATEGORYNAME = "EDIT_CATEGORYNAME";
export const SAVE_CATEGORY = "SAVE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
