export const SET_SUBCATEGORY_LOADER = "SET_SUBCATEGORY_LOADER";
export const SET_SUBCATEGORY = "SET_SUBCATEGORY";
export const ADD_SUBCATEGORY = "ADD_SUBCATEGORY";
export const REMOVE_SUBCATEGORY = "REMOVE_SUBCATEGORY";
export const EDIT_SUBCATEGORY = "EDIT_SUBCATEGORY";
